### ISSUE TITLE
CaloTau not available in CMSSW_11_3_X and CMSSW_12_0_X

### ISSUE THREAD

**Issue by amassiro** [cms-outreach/ispy-analyzers#16]
CaloTau from ISpy/Analyzers/src/ISpyCaloTau.cc is not part of CMSSW anymore.

The compilation fails in any release more recent than 11_3_X.

It may be needed towards Run 3

**Comment by tpmccauley** [comment]
Thanks for opening the issue. Perhaps try the `cmssw11` branch

**Comment by amassiro** [comment]
Great, it compiled in CMSSW_11_3_4

`    git clone https://github.com/cms-outreach/ispy-analyzers.git ISpy/Analyzers  --branch cmssw11
`

For some reason though I needed to delete the following line from  src/ISpy/Analyzers/BuildFile.xml :

```
Parse Error in src/ISpy/Analyzers/BuildFile.xml, line 
Invalid value '$(patsubst %,-DCMSSW_2_2_X,$(findstring CMSSW_2_2,$(SCRAM_PROJECTVERSION)))' found.
```

**Comment by tpmccauley** [comment]
These lines are no longer needed so I have removed them from the BuildFile via https://github.com/cms-outreach/ispy-analyzers/commit/d275bf6ae2d22627480a63ab749d8be487403c9d
